OUTPUT_DIR: "./output/SeqNet-DA2/exp/exp_cuhk_da"
INPUT:
  DATASET: "CUHK-SYSU"
  TDATASET: "PRW"
  DATA_ROOT: "/data1/mustansar/dataset/CUHK-SYSU"
  TDATA_ROOT: "/data1/mustansar/dataset/PRW-v16.04.20/"
  BATCH_SIZE_TRAIN: 5
SOLVER:
  MAX_EPOCHS: 12
  LR_DECAY_MILESTONES: [16]
  BASE_LR: 0.0024
  LW_DA_INS: 0.98
MODEL:
  LOSS:
    LUT_SIZE: 6015
    CQ_SIZE: 5000
EVAL_PERIOD: 2
TARGET_REID_START: 11
EPS_P: 0.98
